### PR TITLE
Check user is on Whatsapp

### PR DESCRIPTION
**Pull request by VanshKela**
#26

### CODE REVIEW

**Comment by Kalebu** [comment]
Hello @VanshKela 

That's a great idea , and works just fine but I think taking 20 seconds to verify if the  user is on WhatsApp  is way long.

How about we implement  this directly  o the find user(methods) so that when it can't  find that user  for 20 seconds  it will count that user as not on WhatsApp .


What do you think ?

**Comment by VanshKela** [comment]
Sorry I don't get what you are asking for we can decrease that 20 seconds wait though.

**Comment by Kalebu** [comment]
I mean think of use case someone to spend 20 seconds just to verify the contact.

So my point why not the above feature implemented  directly  by through existing  methods

1. find_user()
2. & find_by_username() 

Instead of having it as a separate  method, does that makes sense to you ?

**Comment by molder26** [comment]
This is good solution! But, can you do it without taking another 20 sec extra?

**Pull request closed without merging**
