### PR TITLE
allow custom driver

### PR DESCRIPTION
**Pull request by vadolasi**
Allow to use custom drivers (to resolve the #13) and add webdriver-manager to simplify management of binary drivers.

### CODE REVIEW

**Comment by Kalebu** [comment]
Hi @vadolasi, Thanks for another amazing contribution.

I would like for you to clarify some points before merging. 

does this implementation automatically loads the default driver on the path?

Also would you please try to write a bit of documentation with examples showing how the usage gonna lookout during the usage.

**Comment by vadolasi** [comment]
The [webdriver-manager](https://pypi.org/project/webdriver-manager/) package automatically download, unzip and set path of the compatible binary driver. It automates the process described in the "Setting up Selenium" section in the README.

**Comment by Kalebu** [comment]
Hello @vadolasi, Thanks for the clarification

You can also add a bit of docs to readme about it so that it prevent new users from having to setup themselves.

Best regards 
Kalebu

**Comment by vadolasi** [comment]
I edited the readme

**Pull request merged**
